=" USE " + Parameters!DatabasePrefix.Value  + Parameters!DbName.Value
+ " SELECT  si.type, "
+ " schema_name(so.schema_id) AS SchemaName, so.name AS TableName, si.name AS IndexName "
+ "        ,               (CASE is_primary_key WHEN 1 THEN 'PK' ELSE '' END) AS PK "
+ " 		, (CASE is_unique WHEN 1 THEN 'Unique' ELSE '' END) IsUnique "
  
+ "  ,CASE INDEXKEY_PROPERTY(si.object_id, index_id, si.index_id, 'IsDescending')  WHEN 0 THEN 'ASC' WHEN 1 THEN 'DESC' ELSE '' END as ASC_or_DESC, si.type_desc "
+ "   , DS1.[IndexColumnsNames] "
+ "       ,DS2.[IncludedColumnsNames] "

+ "   FROM  sys.indexes AS si  "
+ "   LEFT OUTER JOIN  sys.objects AS so ON so.object_id = si.object_id "
+ "  CROSS APPLY  "
+ " ( "
+ "     SELECT STUFF "
 + "    ( "
 + "        ( "
 + "            SELECT ' [' + CLS.[name] + ']' "
 + "            FROM [sys].[index_columns] INXCLS "
 + "            INNER JOIN [sys].[columns] CLS  "
 + "                ON INXCLS.[object_id] = CLS.[object_id]  "
 + "                AND INXCLS.[column_id] = CLS.[column_id] "
 + "            WHERE si.[object_id] = INXCLS.[object_id]  "
 + "                AND si.[index_id] = INXCLS.[index_id] "
 + "                AND INXCLS.[is_included_column] = 0 "
 + "            FOR XML PATH('') "
 + "        ) "
  + "       ,1 "
  + "       ,1 "
  + "       ,'' "
 + "    )  "
+ " ) DS1 ([IndexColumnsNames]) "
+ " CROSS APPLY  "
+ " ( "
+ "     SELECT STUFF "
+ "     ( "
+ "         ( "
+ "             SELECT ' [' + CLS.[name] + ']' "
+ "             FROM [sys].[index_columns] INXCLS "
+ "             INNER JOIN [sys].[columns] CLS  "
+ "                 ON INXCLS.[object_id] = CLS.[object_id]  "
+ "                 AND INXCLS.[column_id] = CLS.[column_id] "
+ "             WHERE si.[object_id] = INXCLS.[object_id]  "
+ "                 AND si.[index_id] = INXCLS.[index_id] "
+ "                 AND INXCLS.[is_included_column] = 1 "
+ "             FOR XML PATH('') "
+ "         ) "
+ "         ,1 "
+ "         ,1 "
+ "         ,'' "
 + "    )  "
+ " 	) DS2 ([IncludedColumnsNames]) "
+ "   WHERE   si.index_id > 0  AND ISNULL(OBJECTPROPERTY(si.object_id, 'IsMsShipped'),0) = 0 AND so.Name = '" + Parameters!TableName.Value + "' "
+ "   ORDER BY index_id "