


DECLARE @SecondWednesdayInSeptember DATE;

WITH cte1
AS (
    --GENERATE 31 DAYS OF DATES.  THIS IS ENOUGH FOR A SINGLE MONTH.
	SELECT TOP 31 DATEADD(dd, (
				ROW_NUMBER() OVER (
					ORDER BY name
					) - 1
				--THE MONTH IS SET TO SEPTEMBER ('-09-01') OF THE CURRENT YEAR.  IT COULD BE SET TO ANY MONTH OF ANY YEAR.
				), CONVERT(DATE, CONVERT(CHAR(4), DATEPART(yyyy, GETDATE())) + '-09-01')) AS [Date]
	FROM sys.columns
	)
	--SPLIT EACH DAY INTO DATEPARTS.
	,cte2
AS (
	SELECT [Date]
		,DATEPART(yy, [Date]) AS [Year]
		,DATEPART(mm, [Date]) AS [Month]
		,DATEPART(dw, [Date]) AS [DayOfWeek]
	FROM cte1
	)
	--USE ROWNUMBER TO GROUP BY DAY OF WEEK. THE FIRST SEVEN DAYS WILL BE GIVEN THE SEQUENCE OF 1.  MONDAY 1, TUESDAY 1, WEDNESDAY 1, ETC.
	--THE NEXT OCCURRENCE OF MONDAY, WILL BE MONDAY 2, ETC.
	,cte3
AS (
	SELECT *
		,ROW_NUMBER() OVER (
			PARTITION BY [Year]
			,[Month]
			,[DayOfWeek] ORDER BY [Date]
			) AS [SequencedDayOfWeek]
	FROM cte2
	)
SELECT @SecondWednesdayInSeptember = [Date]
FROM cte3
--SELECT THE DAY OF WEEK, USING ITS T-SQL NUMBER, AND WHICH OCCURRENCE IN THE MONTH.  YOU COULD USE ANY DAY AND OCCURRENCE.
WHERE [DayOfWeek] = 4 -- Wednesday
	AND [SequencedDayOfWeek] = 2 -- Second in the month


--THIS IS THE DATE OF THE SECOND WEDNESDAY IN SEPTEMBER OF THE CURRENT YEAR.
SELECT @SecondWednesdayInSeptember

